services:
  - type: web
    name: laravel-api
    env: docker
    repo: 
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: "php artisan serve --host=0.0.0.0 --port=10000"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
